name: Android CI

on:
  pull_request:
    branches-ignore:
      - ''
  push:
    branches-ignore:
      - ''
  workflow_dispatch:

jobs:
  build:
    env:
      FCL_KEYSTORE_PASSWORD: ${{ secrets.FCL_KEYSTORE_PASSWORD }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build debug .apk
      run: |
        chmod +x gradlew
        ./gradlew assembleautobuild
        
    - name : upload apk
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: FCL/build/outputs/apk/autobuild/*
      #  retention-days: 1
